version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hairgg123
      MYSQL_DATABASE: hairgg
      MYSQL_INITDB_SKIP_TZINFO: "1"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./env/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    name: app-network

volumes:
  mysql_data:
