name: CI/CD for Spring Boot

on:
  push:
    branches:
      - feat/cicd  # 특정 브랜치 지정

permissions:
  contents: write  # 레포지토리 내용(코드 포함)에 대한 쓰기 권한
  actions: write  # GitHub Actions 실행 권한
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git 태그 생성 및 푸시
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')" 
          git tag $TAG_NAME
          git push origin $TAG_NAME
      - name: Output으로 태그 전달
        id: output
        run: echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
