name: CI/CD for Spring Boot

on:
  push:
    branches:
      - feat/cicd  # 특정 브랜치 지정

permissions:
  contents: write  # 레포지토리 내용(코드 포함)에 대한 쓰기 권한
  actions: write  # GitHub Actions 실행 권한
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git 태그 생성 및 푸시
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # 태그 이름 생성
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # 환경 변수에 태그 이름 저장

      - name: Output으로 태그 전달
        run: |
          echo "::set-output name=tag_name::${{ env.TAG_NAME }}"  # 출력으로 태그 전달

    outputs:
      tag_name: ${{ steps.output.outputs.tag_name }}  # tag_name 출력
